version: '3.8'

services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/workspace/frontend:cached
      - frontend_node_modules:/workspace/frontend/node_modules
    environment:
      - VITE_API_BASE_URL=/api
    networks:
      - app-network

  backend:
    image: python:3.11-slim-bullseye
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/workspace/backend:cached
    env_file:
      - ./backend/.env.dev
    environment:
      - PYTHONPATH=/workspace/backend
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    command: sleep infinity
    networks:
      - app-network

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend-dev
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  frontend_node_modules:
