version: '3.8'

services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/workspace/frontend:cached
      - frontend_node_modules:/workspace/frontend/node_modules
    env_file:
      - ./backend/.env.dev
    environment:
      - VITE_API_BASE_URL=/api
    working_dir: /workspace/frontend
    networks:
      - app-network

  backend:
    image: python:3.11-slim-bullseye
    ports:
      - "5000:5000"
      - "80:80"
    volumes:
      - ./backend:/workspace/backend:cached
    env_file:
      - ./backend/.env.dev
    environment:
      - PYTHONPATH=/workspace/backend
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    working_dir: /workspace/backend
    command: sh -c "pip install -r requirements.txt && python app.py"
    networks:
      - app-network

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
      - ./backend/static:/workspace/backend/static:ro
    depends_on:
      - frontend-dev
      - backend
    network_mode: "service:backend"

networks:
  app-network:
    driver: bridge

volumes:
  frontend_node_modules:
